-- ALMACENANDO EN LA BD COMO VARBINARY

--		VARBINARY

-- SIN FILESTREAM 

DROP DATABASE IF EXISTS IMAGENES  

CREATE DATABASE IMAGENES

USE IMAGENES 
GO

DROP TABLE IF EXISTS DBO.DOCUMENTOS

CREATE TABLE DBO.DOCUMENTOS (ID INT IDENTITY,
                             NOMBRE VARCHAR(255),
                             CONTENIDO VARBINARY(MAX),
							 EXTENSION CHAR(4)
							 )
GO

INSERT INTO DBO.DOCUMENTOS (NOMBRE,CONTENIDO,EXTENSION)
SELECT 'ARBUSTO', BULKCOLUMN,'JPG'
FROM OPENROWSET(BULK N'C:\IMAGENES\arbusto.jpg', SINGLE_BLOB) AS DOCUMENT
GO
INSERT INTO DBO.DOCUMENTOS (NOMBRE,CONTENIDO,EXTENSION)
SELECT 'FLOR', BULKCOLUMN,'JFIF'
FROM OPENROWSET(BULK N'C:\IMAGENES\FLOR.jpg', SINGLE_BLOB) AS DOCUMENT
GO
SELECT * FROM DBO.DOCUMENTOS 
GO


-------- FILESTREAM

EXEC sp_configure filestream_access_level, 2  
RECONFIGURE  

USE master
GO

DROP DATABASE IF EXISTS IMAGENES  
GO
CREATE DATABASE IMAGENES
GO

USE IMAGENES 
GO

ALTER DATABASE [IMAGENES] 
ADD FILEGROUP [fs_imagenes] CONTAINS FILESTREAM 
GO

ALTER DATABASE [IMAGENES] 
	ADD FILE ( NAME = N'IMAGENES_fs', 
	FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\IMAGENES_fs' ) 
	TO FILEGROUP [fs_imagenes]
GO


USE IMAGENES 
go

DROP TABLE IF EXISTS dbo.DOCUMENTOS_FS  
GO
CREATE TABLE DBO.DOCUMENTOS_FS 
(ID INT IDENTITY,
 ID2 UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL UNIQUE,
 NOMBRE VARCHAR(255),
 CONTENIDO VARBINARY(MAX) FILESTREAM,
 EXTENSION CHAR(4)
)
GO


INSERT INTO DBO.DOCUMENTOS_FS (ID2,NOMBRE,CONTENIDO,EXTENSION)
	SELECT NEWID(),'ARBUSTO', BULKCOLUMN,'jpg'
	FROM OPENROWSET(BULK N'C:\IMAGENES\arbusto.jpg', SINGLE_BLOB) AS DOCUMENT
GO

INSERT INTO DBO.DOCUMENTOS_FS (ID2,NOMBRE,CONTENIDO,EXTENSION)
	SELECT NEWID(), 'FLOR', BULKCOLUMN,'jpg'
	FROM OPENROWSET(BULK N'C:\IMAGENES\flor.jpg', SINGLE_BLOB) AS DOCUMENT
GO

SELECT * FROM DBO.DOCUMENTOS_FS
GO

--- FileTable

USE [master]
GO
ALTER DATABASE [IMAGENES] 
SET FILESTREAM( DIRECTORY_NAME = N'IMAGENES' ) WITH rollback immediate 
GO

USE [master]
GO
ALTER DATABASE [IMAGENES] 
	SET FILESTREAM( NON_TRANSACTED_ACCESS = FULL, 
	DIRECTORY_NAME = N'IMAGENES' ) WITH 
	rollback immediate 
GO


use IMAGENES 
GO
drop table if exists MyDocumentStore
GO
CREATE TABLE MyDocumentStore AS FileTable
WITH
(
    FileTable_Directory = 'MyDocumentStore',
    FileTable_Collate_Filename = database_default,
	FILETABLE_STREAMID_UNIQUE_CONSTRAINT_NAME=UQ_stream_id);
GO


